### ISSUE TITLE
Body font is straining/difficult to read

### ISSUE THREAD

**Issue by ffigiel** [gren-lang/gren-lang.github.io#5]
Hello, and congrats on releasing 0.1 🎉

Copying from Zulip:
Can you reconsider the styling of the body font on the website? There is `font-weight: light` that feels straining to read, especially on a phone. I would suggest bumping the font weight back to regular, making the text color black, or increasing the font size a little

I'm not a designer myself but there are some articles that generally discourage/request caution when using light fonts for body
https://uxmovement.com/content/dos-and-donts-of-using-light-typefaces/
https://blog.prototypr.io/when-the-web-gets-unreadable-2641cd133351

---

I sketched different solutions with browser devtools. The first paragraph is unchanged for comparison.

bumped font weight (I used segoe ui here because the font on the website doesn't include the regular weight)
![gren-lang org_ (3)](https://user-images.githubusercontent.com/4096683/171038923-100455b2-0e98-499e-9cdc-9fd09287d13d.png)

black text
![gren-lang org_](https://user-images.githubusercontent.com/4096683/171038394-76efcb09-b721-4b94-bc56-6757f35bfeee.png)

bumped body text up by 1px
![gren-lang org_ (2)](https://user-images.githubusercontent.com/4096683/171038646-8daf8ad2-452e-43ee-a8bf-c6a6907a435e.png)

**Comment by robinheghan** [comment]
Thank you for this issue.

Just to clarify, which of the three do you prefer?

**Comment by ffigiel** [comment]
I think a regular font weight will work best - it's ubiquitous.

Alternatively, pure black text color would be a second choice. It looks crisp on a light font.

Increasing font size doesn't seem to help much here.
